### ISSUE TITLE
Should libpng dependency be compiled from source?

### ISSUE THREAD

**Issue by lovell** [jcupitt/build-win64#1]
Hi John, it looks like the bundled version of libpng is [1.4.3-1](https://github.com/jcupitt/build-win64/blob/master/8.1/get-win64-packages.sh#L31-L32).

If so, a more up-to-date version that fixes a [number of vulnerabilities](http://libpng.org/pub/png/libpng.html) should probably be used. Is this required/possible?

Thanks!

**Comment by jcupitt** [comment]
There was some reason I didn't build libpng from source, but I forget what it was. I'll check again.

**Comment by jcupitt** [comment]
It's 1.6.19 now, phew!

http://www.vips.ecs.soton.ac.uk/supported/current/win32/vips-dev-w64-8.1.1-3.zip

**Comment by jcupitt** [comment]
.. I forgot to say, I've hardly tested it. Only the png library has changed since `-2`.

**Comment by lovell** [comment]
Marvellous, all working according to https://ci.appveyor.com/project/lovell/sharp/build/276 - thank you John!
