### ISSUE TITLE
update needed for Docker instructions

### ISSUE THREAD

**Issue by dlong500** [jcupitt/build-win64#14]
I finally figured out that the Docker issues I was having all boiled down to running as the root user (not via `sudo`) on my test machine.

I don't know if it is just some Docker settings that cause the problems as I don't have a whole lot of experience with the platform, but if logged in as the actual root user the build process fails once it starts processing the `get-win64-packages.sh` script with permission denied errors upon attempting to create folders.

When running as a non-root user and executing via `sudo` everything works (assuming the build-win64 repo was also cloned under that non-root user account).  The docs do show a `sudo` command, but don't explicitly say that running as the root user directly will fail, so this should probably be mentioned in the README.

**Comment by jcupitt** [comment]
I'm glad it's working!

You (almost) never use admin on linux, except via sudo, but I'll add a note.

**Comment by jcupitt** [comment]
Thanks!

**Comment by dlong500** [comment]
Yeah, I don't typically use root on my production machines, but this was an Ubuntu VM I spun up just for testing the build and was simply being lazy.  I'd still like at some point to figure out why it's failing just out of curiosity, since it's odd to me that it's behaving differently _inside the Docker container_ based on the external user running the command.

In any case, thanks for the feedback.

**Comment by jcupitt** [comment]
Yes, that is a bit odd. Perhaps when you copy files into the container as root they end up unreadable or unwriteable by the docker worker.
