### ISSUE TITLE
Test suite fails with latest win64 build

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/build-win64#18]
The latest (v8.6.3) Windows 64-bit build of libvips fails with the pyvips (and net-vips) foreign test suite. These two tests crashes:
```bash
py.test -q -s tests/test_foreign.py::TestForeign::test_dzsave
py.test -q -s tests/test_foreign.py::TestForeign::test_png
```

The `magickload` test:
```bash
py.test -q -s tests/test_foreign.py::TestForeign::test_magickload
```
 fails with:
```bash
E           pyvips.error.Error: unable to call magickload
E             magick2vips: unable to read file "C:\Users\KleisAuke\Documents\GitHub\pyvips\tests\helpers\..\images\vips-profile.svg"
E           libMagick error: UnableToOpenBlob `C:/Users/KLEISA~1/AppData/Local/Temp/magick-972MQqCAreGY2pP': No such file or directory @ error/blob.c/OpenBlob/2709 (null)
```

I've tried to build it myself (from the master branch of libvips). See the attempt [here](https://github.com/kleisauke/build-win64/tree/build-from-master). Unfortunately, the same problems remain.

Tested with:
```
Windows 10 Pro version 1709 (OS Build 16299.309)
Python 3.6.4
```

With libvips version 8.6.2 and 8.7 pre-release these tests run smoothly. I'm going to set-up AppVeyor for net-vips soon to detect these problems at an early stage.

**Comment by jcupitt** [comment]
Oh dear, thanks for the report. I'll try testing via wine locally.

**Comment by jcupitt** [comment]
I'm seeing a crash inside libz. I'll try rebuilding without the assembler inner loops.

**Comment by jcupitt** [comment]
Yes, that's fixed the libpng crash at least. I'll make a new set of binaries.

**Comment by jcupitt** [comment]
OK, I've uploaded a new pair of win binaries, they fix at least one of the crashes you saw.

**Comment by kleisauke** [comment]
I can confirm that with `8.6.3-1` the whole test suite of pyvips passes:
```
194 passed, 3 skipped in 29.65 seconds
```

:tada: 

Thanks! I'll close this issue.

**Comment by jcupitt** [comment]
\o/
