### ISSUE TITLE
/build.sh: line 34: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by crb912** [jcupitt/build-win64#19]
I run the .sh  script,  but I got an error. 

/build.sh: line 34: syntax error: unexpected end of file

I haven't learn syntax of shell script, could you tell me how to resolve it?

**Comment by jcupitt** [comment]
Hello @crb912,

You need to give more information: what platform are you running on (linux, macos ...), what version, what did you type, what directory were you in?

Are you sure you need to build your own 64-bit Windows binary? There is a pre-built one here:

https://github.com/jcupitt/libvips/releases/tag/v8.6.3

**Comment by crb912** [comment]
Thanks for your immediate feedback!  
I build your code on ubuntu16.04 .  I want to  transplant your vips library to MinGw64 /32 environment on Window platform.
I have a MinGw project (Picture format trans: heif2jpeg) ,  and I need the lib.

Thanks again for your  pre-built version.   :)

**Comment by jcupitt** [comment]
It should build on mingw, you don't need build-win64. Just do configure / make / make install.

The docker stuff is for making a native win64 binary.

**Comment by crb912** [comment]
Thanks a lot.
