### ISSUE TITLE
Static linking of non-LGPL dependencies

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/build-win64#21]
The libvips web binary (`vips-dev-w64-web-8.6.3-1`) currently has 48 DLL files. It would be nice if this could be downsized. It will also be easier for me to pack the libvips binaries in a NuGet package if all non-LGPL dependencies are linked statically.

This may also solve the problem with wrong versions of DLL's being included, like [this issue](https://github.com/jcupitt/ruby-vips/issues/118) what I had a while ago.

`glib`, `libcroco`, `libexif`, `libgsf`, `librsvg`, and `pango` needs to be separated as a shared library because LGPL's basic requirement is to separate the LGPL-licensed library and your own product (I used [this overview](https://github.com/lovell/sharp-libvips#licences) to check which dependencies are LGPL).

I'm not sure if there are any disadvantages with statically linking dependencies in terms of speed and overall DLL size.

**Comment by kleisauke** [comment]
This is difficult to do correctly. I've downsized the libvips web binary (`vips-dev-w64-web-8.6.3-1`) from 48 DLL files to 35 files with https://github.com/jcupitt/build-win64/issues/22.

It's a lot easier to build libvips as a static library, but that may be in violation of the LGPL license. I've added some TODO-notes here: https://github.com/kleisauke/build-win64-mxe

Closing for now. If someone knows how to handle this correctly (in terms of building and LGPL license handling), please let me know.

**Comment by kleisauke** [comment]
I received some comments about the fact that NetVips distributes 37 DLL files. After looking at this again, it seems that building a statically linked DLL does not violate the LGPL license. See: https://stackoverflow.com/a/10179181/10952119

> [Provide everything that allow the user to relink the application with a different version of the LGPL source code](https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic). In this case the other requirements are the same as if it was dynamically linked.

I've made a experiment branch here: https://github.com/libvips/build-win64-mxe/tree/static-linking

After building these DLL files are made:
```
libvips-42.dll		17691 KiB
libglib-2.0-0.dll	 2124 KiB
libgobject-2.0-0.dll	  237 KiB
```
![static-link](https://user-images.githubusercontent.com/12746591/51835169-db6d7f00-22fc-11e9-9337-39867ba62a33.png)

I've built the `GLib` and `GObject` dependencies as shared library to preserve backwards compatibility with the language bindings. I intend to distribute this statically linked library with NetVips 1.1.0.

**Comment by jcupitt** [comment]
Hi, that's right, the aim of the LGPL is to make sure that distributors can't set themselves up as gatekeepers and charge for bug fixes. 

For example, suppose you were to make SuperProduct and charge $100 for it. You use a free library you find called libvips (ahem) to help build it. The libvips devs find an awful bug and release a free fix, SuperProduct incorporate that fix, but only make it available to people who have paid extra for maintenance. 

Now although libvips have put out a free fix, users of libvips are being charged by a third party to get access to it. Disaster! Bad for users, and bad for the libvips devs. 

The LGPL is supposed to make this impossible by requiring that users can always swap out the libvips component for a newer one. The simplest way to do this is just to ship a libvips DLL, but you can also comply by shipping all your unstripped `.o` files, the whole build system, and the build system params for libvips. Now users can rebuild SuperProduct with a newer libvips by building an updated static lib for libvips and then relinking the whole of SuperProduct. 

My feeling is that the DLL solution is so much simpler that static linking is really not worth it, but of course it's your call.

The argument that applies to SuperProduct applies recursively to all LGPL components that libvips uses. To comply, I think you'll need to include:

- all the `.lib`, `.def`, `.a` for each LGPL component used, directly or indirectly, to make the `libvips.dll` you ship
- the libvips build system, including all the flags necessary to build a link-compatible version of each component library
- you mustn't strip the component libs, of course

You'll also need to make sure you are doing the final link and build with freely available software, which I guess you are.

**Comment by cup** [comment]
https://github.com/libvips/build-win64/issues/21
https://github.com/libvips/build-win64-mxe/issues/4
https://github.com/libvips/libvips/issues/1271
