### ISSUE TITLE
How to enable HEIC and AV1 support with this repo?

### ISSUE THREAD

**Issue by Risiamu** [jcupitt/build-win64#40]
I tried to build libvips for win64 with this script (`.build.sh 8.9 all`)but the resulted version have the same problem i mentioned in. https://github.com/libvips/libvips/issues/1738

If anyone can point a direction for me, it would be great help.
Thx in advance.

**Comment by jcupitt** [comment]
Hello @GrandArth,

I'm impressed you've got so far, it's a tricky thing :( I'm sorry it's so difficult.

You need to write a new entry in `vips.modules` for x265. Alternatively, Kleis has HEIC encode enabled in his version of this build system:

https://github.com/libvips/build-win64-mxe

I think I would try that.

**Comment by Risiamu** [comment]
Thx, i will see what i can do.
If i can get this addressed, libvips will be a much more handy tool for me. ^_^

**Comment by Risiamu** [comment]
@jcupitt 
It seems to me that adding a new entry is beyond my current ability.
I never done such thing before, it would cost some extra time that i don't have at the beginning.
MXE version works fine, for now i will go with that.
Thx for the intel.

I will examine the entry after 5 months, when everything is settled.
Thx again for the fast reply.
