### ISSUE TITLE
Build error for 8.11 - missing glib-2.0

### ISSUE THREAD

**Issue by andy250** [jcupitt/build-win64#46]
I am getting this error while running `./build.sh 8.11` on Ubuntu 20.04

```
checking for glib-2.0 >= 2.40 gmodule-no-export-2.0 gobject-2.0 gio-2.0... no
configure: error: Package requirements (glib-2.0 >= 2.40 gmodule-no-export-2.0 gobject-2.0 gio-2.0) were not met:

No package 'glib-2.0' found
No package 'gmodule-no-export-2.0' found
No package 'gobject-2.0' found
No package 'gio-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables REQUIRED_CFLAGS
and REQUIRED_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

Building 8.10 doesn't show this problem (however there are other compilation errors). I tried modifying the dockerfile to install also `libglib2.0-dev` but this didn't help.

**Comment by jcupitt** [comment]
Hi @andy250,

I've not been maintaining this repo for a while, I think we're only using the MXE one now:

https://github.com/libvips/build-win64-mxe

It's pretty similar, it just swaps jhbuild for mxe.

**Comment by andy250** [comment]
Thx, I'll give it a shot. I took the link from here: https://www.libvips.org/install.html#installing-the-windows-binary maybe it could be updated? Also on the bottom there is a link to https://github.com/jcupitt/libvips/wiki/Build-for-Windows --> which redirects back to root of the github repo.

**Comment by jcupitt** [comment]
I'll update those links, thanks!

**Comment by jcupitt** [comment]
OK, updated, thanks for pointing out this link-rot!
